### ISSUE TITLE
Single-source `MeasurementInfo` and `ServiceInfo` in `.serviceconfig` file

### ISSUE THREAD

**Issue by bkeryan** [ni/measurementlink-python#202]
## Problem to Solve

All of the data in the `.serviceconfig` file is duplicated in the `MeasurementInfo` and `ServiceInfo` objects in `measurement.py`. If these files are not in sync, then the measurement service will work correctly when you start it manually but not when you statically register it, or vice versa.

## Proposed Solution

In the `MeasurementService` constructor, allow specifying the path to the `.serviceinfo` file instead of specifying the `measurement_info` and `service_info` parameters. When this is specified, the `MeasurementService` object parses the `.serviceinfo` and automatically constructs `MeasurementInfo` and `ServiceInfo` objects.

This may require additional parameters for `ui_file_paths` and `version` because these are not in the `.serviceconfig` file, or it might require adding these parameters to the `.serviceconfig` file.

[AB#2267348](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2267348)

**Comment by dixonjoel** [comment]
@bkeryan @DelpireNI This issue should be closed now, right?
