### ISSUE TITLE
Merge NI-DCPower examples

### ISSUE THREAD

**Issue by bkeryan** [ni/measurementlink-python#213]
## User Story

Merge `nidcpower_source_dc_voltage` and `nidcpower_source_dc_voltage_with_labview_ui`.
Update the documentation to explain how to switch UIs.

[AB#2273999](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2273999)

**Comment by dixonjoel** [comment]
Fixed with #214
