### ISSUE TITLE
The example TestStand sequences should set the PinMapId to the value returned by the Pinmap Service

### ISSUE THREAD

**Issue by pbirkhol-ni** [ni/measurementlink-python#218]
# Bug Report

The example TestStand sequences call an "Update pin map" action step, which invokes a python code module that updates and/or registers a pinmap with the Pinmap Service. After registering the pinmap, the Pinmap Service will return the PinMapId. The python code module asserts that the ID is the same as the requested ID. However, that is not guaranteed to be the case in a hypothetical future.

## Expected Behavior

The "Update pin map" action step should set the PinMapId temporary global variable to be the PinMapId returned from the Pinmap Service.

## Possible Solution

The "update_pin_map" python function should return a PinMapId. Then the action step should set the return value to the PinMapId temporary global.

![image](https://user-images.githubusercontent.com/57813166/214362785-f0bc4ba2-4c22-4808-aa8f-e4dfdddb6cbf.png)

[AB#2278712](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2278712)

**Comment by jonathanmendez** [comment]
This report originated from a conversation with me. The reasoning is valid if you are using a "Create" method on the pin map service, where you can add a user-provided id but the service-returned id may be different (in a hypothetical future).

However, looking at this more closely, we are using an "Update" method on the pin map service, in which case the supplied id must match an existing id or be used exactly as is (i.e. the service won't return a different id).

So, the existing code is not actually problematic.

In addition, where we may want to improve this in the future would likely be a higher level abstraction anyway (e.g. a custom step type that handles updating the pin map and setting the temporary global variable).

I'm therefore closing this Issue
