### ISSUE TITLE
The python example TestStand sequences will need to be updated to use the newest step type

### ISSUE THREAD

**Issue by pbirkhol-ni** [ni/measurementlink-python#221]
# Bug Report
The TestStand sequences in the examples were saved using a step palette named "NI_MeasurmentFramework.ini". It has since been renamed as "NI_MeasurementLink.ini". This will cause the sequences to load with a Type Conflict message. Not only is this message scary, but it isn't possible for customers to resolve since our step type is password protected. We should make sure our examples resave the sequence files with the latest step type.

[AB#2288802](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2288802)

**Comment by DelpireNI** [comment]
Marking issue as closed. This should be addressed by https://github.com/ni/measurementlink-python/pull/226
