### ISSUE TITLE
Generator produces incorrect reference to serviceconfig when measurement name includes a space

### ISSUE THREAD

**Issue by rfriedma** [ni/measurementlink-python#232]
# Bug Report

I created a new Measurement Plugin using the generator that included a space like "First Measurement" and was unable to run the resulting measurement successfully without modification.

## Repro or Code Sample

1. Generate a measurement using a space
2. Attempt to run the resulting measurement.py without modification
3. You will get an error complaining about a service configuration that doesn't exist

## Expected Behavior

Generated measurements should run out-of-the-box without modification and without error.

## Current Behavior
The generator in almost every instance kept the display name of the measurement plugin "First Measurement" and removed whitespaces for all instances of files and folders "FirstMeasurement". This was as expected. However the measurement.py file included a bad link to a service config that doesn't exist. This causes a run-time error early when launching the measurement.

See screenshot for the problem:
![image](https://user-images.githubusercontent.com/41642157/224442578-5368b162-5121-455f-8213-1eaf8b3ee16e.png)

## Possible Solution

Fix the mako code such that the service config path uses the white-space-free version of the measurement name provided to the ni-measurementlink-generator.

## Context

I was trying to record a demo with a nice display name inclusive of a space and I wasn't able to run it without modification which ran contrary to the ease-of-getting-started message I was trying to deliver. 

## Your Environment

* OS & Device: Windows on VM
* `ni-measurementlink-service` version 1.0.0
* `ni-measurementlink-generator` version 1.0.0
* MeasurementLink version 2023 Q1 final release
* Python version 3.8

[AB#2330904](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2330904)

**Comment by bkeryan** [comment]
When fixing this, let's:
- Change [test_measurement_generator.py](https://github.com/ni/measurementlink-python/blob/main/ni_measurementlink_generator/tests/test_measurement_generator.py) to use whitespace in the service name.
- Rename the example render files to match the generated filenames.
