### ISSUE TITLE
How to open discovery service automatically in every boot

### ISSUE THREAD

**Issue by LawsonGu** [ni/measurementlink-python#267]
Each time I boot the OS, I need to open MeasurementLink Editor fist and then open my measurement service. Else, it could say no discovery service. But this is not elegantly enough. It makes no sence as you are not planning to edit UI but still have to open Editor..... But after discovery service opened, could close Editor, thus I guess discovery service may could open independently.
Is it way I can open discovery service automatically(like set services startup type as automatic)?

AB#2386429

**Comment by bkeryan** [comment]
We are planning to address this in AB#2305696: Launch Discovery Service before registering a Measurement Service when running from a python or LabVIEW development environment.
