### ISSUE TITLE
`_helpers.py` imports internal modules

### ISSUE THREAD

**Issue by bkeryan** [ni/measurementlink-python#333]
# Bug Report

`_helpers.py` imports internal modules. It should only use public APIs.

## Repro or Code Sample

https://github.com/ni/measurementlink-python/blob/main/examples/nidmm_measurement/_helpers.py
```
from ni_measurementlink_service._internal.discovery_client import DiscoveryClient
from ni_measurementlink_service._internal.stubs.ni.measurementlink.pinmap.v1 import (
    pin_map_service_pb2,
    pin_map_service_pb2_grpc,
)
```

## Expected Behavior

Does not import from `_internal`.

## Current Behavior

Imports from `_internal`

## Possible Solution

Move `_discovery_client.py` to `ni_measurementlink_service/discovery_client.py`. Change the old module to emit a deprecation warning and redirect to the new module.

Re-export the `discovery_client` module or the `DiscoveryClient` class from `ni_measurementlink_service/__init__.py`.

Extract stubs into a separate Python package with protobuf standard namespacing (e.g. `import ni.measurementlink.pinmap.v1`). This should use a namespace package to share ownership of `ni`.

## Your Environment

* OS & Device: Windows1
* `ni-measurementlink-service` version: 1.0 - 1.2.0
* MeasurementLink version: N/A
* Python version: N/A

[AB#2457601](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2457601)

**Comment by bkeryan** [comment]
`DiscoveryClient` is in a public module now: `ni_measurementlink_service.discovery`.

The pin map stubs are still internal. AB#2236275 should remove the pin map access from the TestStand code module, so I will reparent this bug under that feature.

**Comment by dixonjoel** [comment]
@bkeryan I took a quick check and these are all gone so closing this.
