### ISSUE TITLE
`MeasurementService` class attributes leak internal types

### ISSUE THREAD

**Issue by bkeryan** [ni/measurementlink-python#334]
# Bug Report

The `MeasurementService` class has public attributes with private/internal types.

## Repro or Code Sample

https://github.com/ni/measurementlink-python/blob/main/ni_measurementlink_service/measurement/service.py#L125
```
    Attributes
    ----------
        measurement_info (info.MeasurementInfo): Measurement info

        service_info(info.ServiceInfo) : Service Info

        configuration_parameter_list (List): List of configuration parameters.

        output_parameter_list (list): List of output parameters.

        measure_function (Callable): Registered measurement function.

        context (MeasurementContext): Accessor for context-local state.

        discovery_client (DiscoveryClient): Client for accessing the MeasurementLink discovery
            service.

        channel_pool (GrpcChannelPool): Pool of gRPC channels used by the service.

    """
```

## Expected Behavior

All public attributes have public types.

## Current Behavior

`configuration_parameter_list` and `output_parameter_list` have an underspecified type signature. They are really lists of `ni_measurementlink_service._internal.parameter.metadata.ParameterMetadata`, but that is an internal type.

`discovery_client` has an internal type.

`measure_function` is arguably an internal attribute, even though it doesn't leak any internal types.

## Your Environment

* OS & Device: Windows
* `ni-measurementlink-service` version: 1.0 through 1.2.0-dev0
* MeasurementLink version: N/A
* Python version: N/A

[AB#2457615](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2457615)

**Comment by dixonjoel** [comment]
@bkeryan would it be better to treat this as a tech debt since it involves some refactoring to the internals? It's showing up on our > 28d list in AzDO.

**Comment by bkeryan** [comment]
> @bkeryan would it be better to treat this as a tech debt since it involves some refactoring to the internals? It's showing up on our > 28d list in AzDO.

No, this problem is user-visible, not technical debt.
