### ISSUE TITLE
Python repo need to have a sub module repo that contains the proto file.

### ISSUE THREAD

**Issue by Vasantha-Kumar-J** [ni/measurementlink-python#42]
Currently the proto files are only available in [Azure Repo](https://dev.azure.com/ni/DevCentral/_git/ASW?path=/Source/MeasurementServices/proto). But the protos are common for Azure, Labview , and Python measurement service repos. need to move protos to a individual repo and add it as a sub module to the python repo.

Related item: 

- [ ]  Update the `Updating gRPC stubs when a .proto file is modified` section in Contributing.md. 

[AB#2267424](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2267424)

**Comment by dixonjoel** [comment]
Tracked elsewhere as an NI company effort.
