### ISSUE TITLE
Remove `SESSION_MANAGEMENT_2024Q1` feature toggle in 1.4

### ISSUE THREAD

**Issue by bkeryan** [ni/measurementlink-python#516]
## Tech Debt

`SESSION_MANAGEMENT_2024Q1` is enabled by default in 1.3 and should be removed in 1.4.

[AB#2577651](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2577651)

**Comment by Jayaseelan-James** [comment]
#611 completes the necessary work.
