### ISSUE TITLE
Remove the UI Progress Updates example

### ISSUE THREAD

**Issue by pbirkhol-ni** [ni/measurementlink-python#534]
# Bug Report

The Game of Life example shows how to do continuous updates. There is no need to have it shown in two examples. Some things to consider:
- The Game of Life doesn't do cancellation. Consider adding it.
- Mention in the example Readme that the Game of Life example shows how to do UI progress updates.

[AB#2594787](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2594787)

**Comment by bkeryan** [comment]
Let's also remove sample_streaming_measurement. It was added to support automated tests, but now the tests have a fork of this code.
